### PR TITLE
Add spec for threads

### PR DESCRIPTION
**Pull request by oed**
This PR adds a specification for the upcoming threads feature which enables p2p communication between multiple 3Box users.

### CODE REVIEW

**Comment by bmann** [comment]
Hey have you considered following the ActivityPub spec? 

This write up from Mastodon has useful background https://blog.joinmastodon.org/2018/06/why-activitypub-is-the-future/

**Comment by oed** [comment]
Hey @bmann, thanks for your comment! This is actually the first time I hear about ActivityPub. From looking at the document you linked from Mastodon it seems like ActivityPub assumes that you have a server. 3Box (and OrbitDB/libp2p which we use under the hood) don't make the assumption that there is a server anywhere. So if two people are online at the same time they could have a Thread between them without needing the data to be stored on a server explicitly. Then of course there could be servers added to this for data persistence and availability.  

Hope that answers your question! 😊

**Comment by bmann** [comment]
I guess I should be more specific. Rather than re-inventing the social web again, there is lots to learn from ActivityPub.

Web bridges / relayers might be ActivityPub compliant, which is out of scope for you — but you might find some inspiration. 

The data format / structures of the social web are defined in ActivityStreams https://www.w3.org/TR/activitystreams-core/

If you use an existing data format, people will be able to do interoperability a lot easier.

**Comment by oed** [comment]
Thanks for the link @bmann I'm sure it would be possible to either:
* put ActivityStream formated entries into our data format (which is a hash linked CRDT)
* create an adapter that converts data in threads to ActivityStreams

My main issue with the ActivityStream format is that it relies on JSON-LD which in turn relies on http links, which are inherently mutable. We believe that the future of the web is content addressable, not location addressable.

**Comment by bmann** [comment]
I agree! We used to say “cool URLs never change”. With content addressing they never do, by default!

Just looked at the spec https://www.w3.org/TR/json-ld11/

It references URIs, which are protocol agnostic. The examples use mainly http URIs.

I looked up URIs and what IPFS thinks and there is a thread from 3 years ago:

https://github.com/ipfs/go-ipfs/issues/1678

Will ask around for what the view is today.

**Comment by oed** [comment]
Oh nice! Then JSON-LD is definitely more interesting.

Ipfs is defining their own format called IPLD, but it's currently not finalized afaik.

**Comment by michaelsena** [comment]
Approved @oed

**Pull request merged**
