### PR TITLE
Update community projects - add linkedref in.

### PR DESCRIPTION
**Pull request by IMRFeng**
Added linkedref.io project in

### CODE REVIEW

**Comment by michaelsena** [comment]
Hey @IMRFeng, thanks for your submission! :tada: I tried the link you provided, https://linkedref.in but I wasn't able to get your site. I saw a namecheap landing page. Any ideas?

**Comment by oed** [comment]
Hey @IMRFeng checking in again. Is this an active project that you'd like to get listed here?

**Comment by IMRFeng** [comment]
Hi @oed, sorry for this delayed message. Yes, it's an active project but it's still in internal testing stage, not ready online yet. Does this have to be an online project?

**Comment by oed** [comment]
@IMRFeng I would say so yes. What do you think @michaelsena?

**Comment by IMRFeng** [comment]
@oed but in the requirements of the bounty it mentions "or dapp code that has successfully integrated with 3Box methods mentioned above" which meant it might not be an online project? correct me if I'm wrong.

**Comment by michaelsena** [comment]
I don’t have the copy of the original bounty so it’s hard for me to look back. I would say the intent of the bounty was for it to be an online project so that we and others could try it, but if I left that off the bounty we will still honor it. @oed @imrfeng

**Comment by IMRFeng** [comment]
Hi @michaelsena, thanks for your reply. The bounty link is https://explorer.bounties.network/bounty/1923.

**Comment by charlesmorgan40** [comment]
IMRFeng:projects/linked-ref

**Pull request closed without merging**
